### ISSUE TITLE
Everything is gone!

### ISSUE THREAD

**Issue by khepin** [RobinHerbots/jquery.inputmask#1]
I'm not sure if this was intentional or not, but all the code is gone from this repo right now.

Can you check what happened or let us know why you removed it if it was intentional?

**Comment by RobinHerbots** [comment]
@khepin ,

Don't worry !!  The inputmask code is at https://github.com/RobinHerbots/Inputmask.

This is a new repo with the integration with jquery.  So actually this will be the home of the jquery plugin soon.
