### ISSUE TITLE
Uncaught InternalError: too much recursion freezes the browser

### ISSUE THREAD

**Issue by Granada2013** [RobinHerbots/jquery.inputmask#2570]
Hello Robin,

I receive the following regexp from the backend and put it in the inputmask: '\\w+@[a-zA-Z_]+?\\.[a-zA-Z]{2,6}' 
Inputmask({
        regex: '\\w+@[a-zA-Z_]+?\\.[a-zA-Z]{2,6}' ,
      }).mask(currentInput);

The browser then freezes and I catch the following error in console: **Uncaught InternalError: too much recursion**
![изображение](https://user-images.githubusercontent.com/60459373/144577669-2a080693-86b6-4aeb-b101-7e64bbe8e2b8.png)

I assume the problem is because of lazy quantifyer +?. If I delete the ?-sign  everything works ok. Is it really so?
Since I can't influence on what I receive from the backend is there something I can do to avoid this error, any known workaround?

Thank you.

- Browser: Firefox
- Inputmask version: 5.0.1

**Comment by RobinHerbots** [comment]
@Granada2013 ,

Can you have a try with 5.0.7-beta.35.
There was an error in the mask-lexer.js

**Comment by Granada2013** [comment]
It's fixed after update to 5.0.7.
Thank you!
