### ISSUE TITLE
ChromeOS issues with onscreen keyboard resulting from failure to pass valid keyCode

### ISSUE THREAD

**Issue by ktvfe** [RobinHerbots/jquery.inputmask#2572]
- Describe the bug

I am trying to use this library on a chrome os device with the on screen touch keyboard (not a physical keyboard) and am having issues. It seems that chrome os does not pass the correct keyCode which is used extensively. Instead keyCode is always 0. I believe this article describes what I am seeing 

https://stackoverflow.com/questions/8942678/keyboardevent-in-chrome-keycode-is-0/12522752#12522752

This points to the following spec that states the keyCode event while having near universal support is deprecated. 

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

It would seem that maybe in the case of keyCode = 0 it needs to be handled in a different way.  You can type in the field but the mask is pushed and not honored at all when used as the key event is called but not processed correctly.

I did try using the inputEventOnly="true" flag which says it is for debug testing only and that seems to make things mostly work. The problem I ran into is this does not seem to handle the backspace key correctly when it encounters the / in a date field.

I'm continuing to look into this and can provide screenshots or other information as needed.  

- Add a link to a codepen, jsfiddle or other example page which shows the problem
https://robinherbots.github.io/Inputmask/ - since the issue is OS dependent I'm not certain I can create a better example.

- OS:
ChromeOS / I am recreating using cloudready but I believe any Chromebook will have the same issue

- Browser
Chrome

- Inputmask version
5.x and now testing using latest code from git repo

**Comment by ktvfe** [comment]
This patch seems to fix the issue that we are seeing when working with dates and using the backspace in inputEventOnly mode.

It does slightly change the behavior when not in inputEventOnly mode, but I believe the change may be beneficial. It changes the behavior when you have a partially completed date such as "11/11/yyyy" and you select (highlight) the second slash character then press the backspace. Previously it would place the cursor after the slash. Now it will place it in front of the slash. (In both cases this is different from the behavior if the cursor is after the slash and no character is selected.)

We have not yet fully evaluated the effect on other input masks.

We believe it is likely that this may adversely affect behavior if the field is configured for right to left reading and there may be a better way to fix and handle that. It is possible this is already handled by the reversal of the value of k at the beginning of the function.

This behavior defaults to "lvp" for postionCaretOnClick when calling determineNewCaretPosition() from handleRemove(). It is possible that it would be better to default to undefined or opts.postionCaretOnClick (as the current behavior in determineNewCaretPosition).

We would definitely be interested in your feedback on this fix and whether you feel it would be reasonable to switch to using inputEventOnly="true" or if this would potentially cause problems in other browsers.

[handle_backspace.zip](https://github.com/RobinHerbots/Inputmask/files/7655102/handle_backspace.zip)

**Comment by RobinHerbots** [comment]
@ktvfe ,

Using the inputeventonly option is a valid option as it is used on every mobile device (or should be)
On which kind of device are you using the ChromeOS?  I need a way to detect wheter a virtual keyboard  is used or a physical.

For the backspace handling for ex Dates.  This is not related to the ChromeOS issue.  I tested, with and without the inputeventonly option.  It would indeed be more logical that the caret is before the / in this case.  I will have a look at your patch.

**Comment by RobinHerbots** [comment]
@ktvfe ,

With this mask you can reproduce the backspace bug.
´´´
  Inputmask("99-99", {
            inputEventOnly: true,
            insertMode: false
        }).mask("test2");
´´´

**Comment by ktvfe** [comment]
I am using just cloudready (https://www.neverware.com/freedownload#home-edition-install) off a usb to reproduce with my pc. I think any chromeos device can be used to reproduce by selecting the onscreen keyboard and not using the physical keyboard. As this is the default behavior on chromeos tablets (not full pc replacements) I think it will be more prevalent there. I am trying to find the model it was first seen on.

I am also trying to get a pull request together. I think the patch changed just  a slight amount to handle delete and safari potentially better. I am working on testing that. Sorry for the delay and thank your for looking at this and verifying you can reproduce behavior.

**Comment by ktvfe** [comment]
This appears fixed in 5.0.8. Thank you.
