### ISSUE TITLE
Minus sign can't be entered into currency field

### ISSUE THREAD

**Issue by toxpal** [RobinHerbots/jquery.inputmask#2583]
When field alias is set to "currency", minus sign can't be entered manually. It works when value is set using HTML tag (`value="-1.00"`), but entering it directly is impossible. The last version which works is 5.0.5, later versions don't work.

**Comment by RobinHerbots** [comment]
@toxpal ,

Can you have a try on the demo page?  I've tested and it works.  Or is this on a specific platform?

**Comment by toxpal** [comment]
Doesn't work on demo page for me. Tested using latest versions of Vivaldi and FireFox, running Manjaro Linux KDE.

P.S. Just found that it **partially** works. If I use minus symbol from the top row of keyboard (just below all the F1-F12 keys), it works. However, I always prefer using minus symbol from the right side of keyboard (that small numeric keypad), and this one doesn't work with 5.0.5+ versions. The same applies to number (integer/decimal) aliases.

**Comment by RobinHerbots** [comment]
@toxpal ,

Ok, thx for the extra info.  I will check why it doesn't work from the keypad.

**Comment by RobinHerbots** [comment]
@toxpal ,

Fixed in 5.0.8-beta.2

**Comment by toxpal** [comment]
Thanks, will check it once released.
