### ISSUE TITLE
A caret switcher before after radix, able to trigger programmatically (Caret Fix For Android Mobile Devices)

### ISSUE THREAD

**Issue by BerkerYuceer** [RobinHerbots/jquery.inputmask#2585]
Hi thanks for this great plugin,

I have an issue with decimal places. Some mobile devices uses ',' as decimal seperator so when we click at that caret moves to decimal place as intended. However in some spesific mobile devices input only allows '.' as decimal seperator and we are stuck at that point. So what I am looking for is a method that would allow me to move caret to decimal place as in your code when I trigger the event. A caret switcher before after radix, able to trigger programmatically.

If there is already an easier method for this that I haven't seen in your documentation, would gladly apply that.

I narrowed the issue to this: when input has value 0,00 using '.' to dance radix wont work and also on Android devices u cant detect '.' Keypress however u can detect input value after keypress. 

An extra optional char that can dance radix would solve this issue

**Comment by BerkerYuceer** [comment]
Long story short Android has issues about this radix point being ',' instead of '.' so we need an option to make this '.' button trigger as ',' to work on Android devices. Please note that Android automatically blocks ',' and only allows '.' button to be used on numeric input fields. Changing input type might be a bad idea cause we gonna loose the big number buttons and receive an entire keyboard with chars instead.

For those who might have the same issue I have a workaround which is not elegant at alI. First I detected the OS checked if it is 'Android' then added $.attr('inputmode', 'tel') to bring ',' with numbers on android keyboard which is far from a solution actually.

Waiting for a proper solution for this such as { AndroidRadixFix: true; }

**Comment by RobinHerbots** [comment]
@BerkerYuceer ,

Which version of the inputmask are you using?

**Comment by BerkerYuceer** [comment]
@RobinHerbots sorry I couldn't answer earlier, I been trough a lot lately... (covid and stuff... )
The version I am using is : Version: 5.0.6

To be able to create the issue what you need is a .net platform webforms project. 
Just because I am providing Turkish language the format should be '1.000,00' yet sadly 
on Android devices keypad comes with '.' instead of ',' and does not allow me to put ',' on my currency input.
to be able to cover such problem I suggest making a second decimal seperator trigger.
('.' usage to act as ',') an optional parameter to dance the redix could solve a lot issues.

even though the decimal seperator targetted as ',' using a second trigger as '.' should not cause 
any trouble on automated thousand seperator filling.

**Comment by BerkerYuceer** [comment]
How I dealt with it so far is a mess.. I use some css hacks to convert Android keypad from currency to phone. That way Android will allow ',' usage in keypad. This is a problem with Android it self but if we allow a second trigger, there are detection methods that will allow us to detect OS and change input attributes for it. Regardless of what user choose to enter as a seperator ('.' or ',') we will auto fill the format as we wanted.

**Comment by RobinHerbots** [comment]
@BerkerYuceer ,

Upgrading to version 5.0.7 should fix your issue.  (Character substitution )

**Comment by BerkerYuceer** [comment]
It actually did fix it. Thank you very much great sir! :)
