### ISSUE TITLE
Incorrect behavior of numeric mask with custom radixPoint

### ISSUE THREAD

**Issue by mkorshikov** [RobinHerbots/jquery.inputmask#2587]
When using a radixPoint other than a dot, the decimal part of the number goes into groups
Example: https://jsfiddle.net/7xkzao21/

```
<input type="text" id="test1" value=1111.234>
<input type="text" id="test2" value=1111.234>

$(document).ready(function(){
 $('#test1').inputmask('numeric', {
    	radixPoint: '.',
	groupSeparator: ' ',
  });
  $('#test2').inputmask('numeric', {
    	radixPoint: 'x',
	groupSeparator: ' ',
  });
});
```

test1 input displays: "1 111.234"
test1 input displays: "1 111 234"

OS: Win 10 (all)
Browser: Chrome 97 (all)
Inputmask versions: 3.3.11,  5.0.8-beta.3

**Comment by RobinHerbots** [comment]
@mkorshikov ,

Have a read https://github.com/RobinHerbots/Inputmask/blob/5.x/README_numeric.md#inputtype
