### ISSUE TITLE
Bug with numerical a keyboard (negative signals)

### ISSUE THREAD

**Issue by marcoaurelioneto** [RobinHerbots/jquery.inputmask#2588]
- Describe the bug
When i input negative signal in numeric keyboard the field change to max value.
But, when i input minus in keyboard (above the letters), the behavior is correct. The field insert negative signal.

- Add a link to a codepen, jsfiddle or other example page which shows the problem
https://jsfiddle.net/marcoaurelioneto/tudaso9r/4/

- OS:
MacOS 12.1 and Linux Pop OS 20.04

- Browser
Google Chrome 97.0.4692.99

- Inputmask version
5.0.7 and 5.0.8-beta.1

**Comment by RobinHerbots** [comment]
Can you try with the latest.  This is already been fixed.

**Comment by marcoaurelioneto** [comment]
Sorry, what the latest version?

I thought 5.0.8-beta.1 was the last version and the problem still persistent in this version.

**Comment by marcoaurelioneto** [comment]
I had test in 5.0.8-beta.7 version and is working.

I'm closing this issue. Thaks.

**Comment by limdv** [comment]
Hello,
I am having the same issue with the 5.0.7 NuGet package, is there going to be a 5.0.8 release to pull?
