### ISSUE TITLE
Robin Herbots InputMask bug or error?

### ISSUE THREAD

**Issue by Nordland1972** [RobinHerbots/jquery.inputmask#2589]
Hello all,

I am new to this site - so I hope that it is okay to write the following... :

I have tried to make use of this Inputmask in my ASP .NET and C# project and make my own JS-file which inherits from RobinHerbots. I have a project with a masterpage and several childpages - but I'm wondering that I only can get this Inputmask to work in some of my childpages. I have tested my own coding - and can't find any differences in my childpages. I can inform that I have make use of UpdatePanel's in my project wherein I have made use of the alias. I have tried to make the following code in a new inherited file, where I have created my own alias:

// Code begin in my own JS-file (FreEconomicInputmask.js)
var customInputmask = (function () {
    var config = {
        extendDefaults: {
            showMaskOnHover: true,
            showMaskOnFocus: true
        },
        extendDefinitions: {},
        extendAliases: {
            'FreEconomic-datetime': {
                alias: "datetime",
                inputFormat: "dd.mm.yyyy"
            },
            'FreEconomic-decimal': {
                alias: 'currency',
                prefix: '',
                radixPoint: ',',
                groupSeparator: '.',
                autoGroup: false,
            }
        }
    };
    var init = function () {
        Inputmask.extendDefaults(config.extendDefaults);
        Inputmask.extendDefinitions(config.extendDefinitions);
        Inputmask.extendAliases(config.extendAliases);
        $('[data-inputmask]').inputmask();
    };
    return {
        init: init
    };
}());
$(document).ready(function () {
    customInputmask.init();
}());
// Code end

I have enabled the following Js-files:
    <script type="text/javascript" src="Inputmask-5.x/dist/jquery.inputmask.js"></script>
    <script type="text/javascript" src="Inputmask-5.x/dist/query.js"></script>
    <script type="text/javascript" src="Inputmask-5.x/dist/bindings/inputmask.binding.js"></script>
    <script type="text/javascript" src="JavaScript/FreEconomicInputmask.js"></script>

And at least I have make use of the inputmask in my TextBox in this way:
data-inputmask="'alias': 'FreEconomic-datetime'"

So my question is: Is there a bug or am I missing something to get  this inputmask to work with my coding in my own JS-file in all my childpages?

Regards Michael

**Comment by Nordland1972** [comment]
After a while I found out that it was an outer UpdatePanel inC# that causes the error - so I have changed this to a normal Panel in C# and everything works fine.

**Comment by RobinHerbots** [comment]
Sorry that I didn't reply before.

But you found a solution, that's the most important.
