### ISSUE TITLE
Currency - set the amount of numbers before the decimal places

### ISSUE THREAD

**Issue by BryanSOliveira** [RobinHerbots/jquery.inputmask#2590]
I want to set the amount of numbers before the decimal places. for example, set 5 places before decimals and 2 digits:

00000.00

I've been trying, but by default it's only gone two places before the decimal places.

it is possible?
thanks!

version 5.0.8-beta.7
google chrome browser

![image](https://user-images.githubusercontent.com/72510251/153329388-7c2b8c03-f943-4e96-b8c9-03563249c0e6.png)

`<input ref="inpMask" data-inputmask-alias="currency" data-inputmask-numericInput="true" 
        data-inputmask-digits="2">`

**Comment by RobinHerbots** [comment]
@BryanSOliveira ,

Maybe something like this:

```
<input id="test1" data-inputmask-mask="99999.99" data-inputmask-numericinput="true" data-inputmask-placeholder="0"/>
```

**Comment by BryanSOliveira** [comment]
@RobinHerbots, 

Thanks!
