### ISSUE TITLE
Delete caret cursor datetime

### ISSUE THREAD

**Issue by SrgGs** [RobinHerbots/jquery.inputmask#2591]
Hello

how to remove this selection so that there is only the cursor?

<img width="102" alt="image" src="https://user-images.githubusercontent.com/6164822/153408674-3081e0e8-3385-44d6-ba12-0f603a2f129d.png">

	alias: 'datetime',
	inputFormat: 'HH:MM',

**Comment by RobinHerbots** [comment]
@SrgGs ,

See https://github.com/RobinHerbots/Inputmask/blob/5.x/README.md#insertmode and https://github.com/RobinHerbots/Inputmask/blob/5.x/README.md#insertmodevisual
