### ISSUE TITLE
groupSeparator changes automatically if the number is minus hundreds of thousands round

### ISSUE THREAD

**Issue by Skematografi** [RobinHerbots/jquery.inputmask#2592]
- my settings:
```
$('.input-decimal').inputmask({
       alias: 'decimal',
       number: 4,
       Group separator: '.',
       root point: ',',
       allowMinus: true,
       AutoGroup: true,
       removeMaskOnSubmit: false,
       right aligned: false,
   });
```

problem :
when my calculation function returns the number -100.000 / hundreds of thousands, the separator changes to a comma (,) => -100,000

but if the result is -100.000,55 / hundreds of thousands of decimals accordingly => -100.000,55

**Inputmask version 3.3.8**

**Comment by RobinHerbots** [comment]
@Skematografi ,

Upgrade to a newer version and read https://github.com/RobinHerbots/Inputmask/blob/5.x/README_numeric.md
