### ISSUE TITLE
Cannot read property 'maxTouchPoints' of undefined

### ISSUE THREAD

**Issue by kaushik3pg** [RobinHerbots/jquery.inputmask#2594]
Whenever trying to build the next project, the error is coming : Cannot read property 'maxTouchPoints' of undefined.
See the screenshot below
![image](https://user-images.githubusercontent.com/83402645/156305584-54280525-28c3-486d-a372-065e96b3dba7.png)

Other Details : 
OS: Windows 10(this shouldn't matter though)
Browser : Chrome(latest)(this shouldn't matter though)
Inputmask version : 5.0.8-beta.1
(Also, tried with 5.0.8-beta.15)

PS. If resort to last stable version of inputmask i.e. 5.0.7( then a new build error "self is not defined" comes, because of which I had to use the beta version in the first place.
@RobinHerbots

**Comment by saqibn** [comment]
having the same issue

**Comment by architsajjan** [comment]
I am also facing the same issue

**Comment by kaushik3pg** [comment]
Thanks @RobinHerbots for your help. Any idea when 5.0.8-beta.17 would be updated to npm?(We are in urgent need of this fix as our builds fail without this and no code is getting merged.) Thanks again for all the help and support.

**Comment by RobinHerbots** [comment]
Done

Op wo 2 mrt. 2022 11:56 schreef kaushik3pg ***@***.***>:

**Comment by kaushik3pg** [comment]
Thanks. Really appreciate this.
