### ISSUE TITLE
DateTime milliseconds

### ISSUE THREAD

**Issue by sanyi9305** [RobinHerbots/jquery.inputmask#2597]
Hi!

I would like dateTime format with "l" milliseconds, but I don't get back the full length.
- I use this:
Inputmask.unmask("2022.03.08 09:30:12.123", { alias: "datetime", inputFormat: "yyyy.mm.dd HH:MM:ss.l",  outputFormat: "yyyy.mm.dd HH:MM:ss.l" });

I get this:
'2022.03.08 09:30:12.1'

- OS: Windows 10
- Browser: Chrome Version: 99.0.4844.51 64 bit, Firefox 97.0.2 64 bit
- Inputmask version Version: 5.0.8-beta.15 

I think this solve the problem eg:
lll: ["[0-9]{3}", Date.prototype.setMilliseconds, "milliseconds", function() {
        return w(Date.prototype.getMilliseconds.call(this), 3)
 }
],

**Comment by RobinHerbots** [comment]
@sanyi9305 ,

This is fixed in 5.0.8-beta.19
