### ISSUE TITLE
Problem with code +972

### ISSUE THREAD

**Issue by devyatinka** [RobinHerbots/jquery.inputmask#2601]
I need a mask for Israel tel numbers and mask should begin from +972, but "9" is default number and all time plugin remove "9" from country international code "+972". How I can solve this issue ?

**Comment by RobinHerbots** [comment]
@devyatinka ,

You need to escape the 9 as it is also used as a definition for numbers.  =>   +\\\\972

**Comment by devyatinka** [comment]
> @devyatinka ,
> 
> You need to escape the 9 as it is also used as a definition for numbers. => +\\972

**Comment by devyatinka** [comment]
Thanks, I did it!
