### ISSUE TITLE
getemptymask returns a reversed string in 5.x

### ISSUE THREAD

**Issue by kris-owens** [RobinHerbots/jquery.inputmask#2605]
In 4.x calling `.inputmask('getemptymask')` would return the mask in the correct order, like prefix + mask + suffix. In 5.0.0 and higher it's now returning with the string reversed.

For example for the mask below getemptymask should return `abc 0 xyz` but returns `zyx 0 cba`.
```
$('.a').inputmask({
  alias: 'numeric',
  prefix: 'abc ',
  suffix: ' xyz',
});
```

With 4.x: [https://jsfiddle.net/60snpfzy/8/](https://jsfiddle.net/60snpfzy/8/) (this appears to be missing the first character as well)

With 5.x: [https://jsfiddle.net/60snpfzy/7/](https://jsfiddle.net/60snpfzy/7/)

**Comment by RobinHerbots** [comment]
Fixed
