### ISSUE TITLE
Numpad negative sign is wrong 

### ISSUE THREAD

**Issue by sanyi9305** [RobinHerbots/jquery.inputmask#2606]
Hi,

Thank you this library, this is very good!
Can you help me?

I have this format:
**alias**: "decimal"
**allowMinus**: true
**autoGroup**: true
**clearMaskOnLostFocus**: false
**digits**: 2
**digitsOptional**: false
**greedy**: false
**groupSeparator**: ","
**groupSize**: 3
**max**: "9999.99"
**min**: "-9999.99"

When the value is "1.00" (or anything else) in the input field and I pressed "-" key on numpad the value is change to "9,999.99"(maxvalue)
But when I pressed not numpad "-" this Is will working good.

OS: Windows 10
Browser: Chrome Version: 99.0.4844.51 64 bit, Firefox 97.0.2 64 bit
Inputmask version Version: 5.0.8-beta.15

**Comment by RobinHerbots** [comment]
@sanyi9305 ,

Can you give me the output of e.location in the keydown event.

Are you using a special keyboard?

Best regards,
Robin

**Comment by RobinHerbots** [comment]
It has todo with 

```
        onKeyDown: function (e, buffer, caretPos, opts) {
            var $input = $(this), bffr;
            if (e.location != 3) {
                var pattern, c = String.fromCharCode(e.keyCode).toLowerCase();
                if ((pattern = (opts.shortcuts && opts.shortcuts[c]))) {
                    if (pattern.length > 1) {
                        this.inputmask.__valueSet.call(this, parseFloat(this.inputmask.unmaskedvalue()) * parseInt(pattern));
                        $input.trigger("setvalue");
                        return false;
                    }
                }
            }
```
This can be found in the inputmask.numeric.extensions.js

**Comment by sanyi9305** [comment]
> @sanyi9305 ,
> 
> Can you give me the output of e.location in the keydown event.
> 
> Are you using a special keyboard?
> 
> Best regards, Robin

I have a normal keyboard.

**e.location: 3**

**Comment by RobinHerbots** [comment]
@sanyi9305 ,

Hmm I cannot reproduce the issue here.

Can you workout an example in a codepen or something.

**Comment by sanyi9305** [comment]
> @sanyi9305 ,
> 
> Hmm I cannot reproduce the issue here.
> 
> Can you workout an example in a codepen or something.

Yes.
https://codepen.io/sanyi9305/pen/popPQvP

**Comment by sanyi9305** [comment]
OMG!
Sorry this is my fault, I changed the library to 5.0.7 this was the problem :(
This works well in the latest beta.
Thank you for your help.

**Comment by RobinHerbots** [comment]
@sanyi9305 ,

No problem.  I'm glad the issue is resolved!
