### ISSUE TITLE
empty placeholder, problem mask with dash

### ISSUE THREAD

**Issue by SrgGs** [RobinHerbots/jquery.inputmask#2607]
mask: '999-999-999',
	placeholder: '',
	
start:
<img width="388" alt="image" src="https://user-images.githubusercontent.com/6164822/160816775-c77f8c1f-1baa-4746-afc4-a9c8d9ba958d.png">

but I want the dashes to add automatically when I add characters

that is:

start empty:

adds a character, second character, third character

A DASH IS ADDED

adds a character, second character, third character

A DASH IS ADDED

<img width="194" alt="image" src="https://user-images.githubusercontent.com/6164822/160817903-550ffadc-cd4e-44fe-9765-24bf512460b0.png">

**Comment by RobinHerbots** [comment]
@SrgGs ,

Try with https://github.com/RobinHerbots/Inputmask#jit-masking
