### ISSUE TITLE
Useless condition

### ISSUE THREAD

**Issue by olegbaturin** [RobinHerbots/jquery.inputmask#2617]
Useless condition `if (true) {}` at this [line](https://github.com/RobinHerbots/Inputmask/blob/af6120051c11b9c7416b4e756ea7f44ae639d8f2/lib/extensions/inputmask.date.extensions.js#L337)
5.0.8-beta.17

**Comment by RobinHerbots** [comment]
@olegbaturin ,

It is not that useless as it seems.  It is used to check wheter the datetime is valid.
An invalid date object returns NaN for getTime() and NaN is the only object not strictly equal to itself.

But I agree that using isnan makes the code more readable/better.

I pushed an update.
