### ISSUE TITLE
Optional value on Country Code

### ISSUE THREAD

**Issue by xts-velkumars** [RobinHerbots/jquery.inputmask#2619]
Hi, 

Can I achieve like below? 

`$('#test').inputmask('(99[9]) 99999-99999')`

**Comment by RobinHerbots** [comment]
@xts-velkumars ,

You have 2 options.

You use version 5.0.8-beta.23 and add the keepStatic: true option.

$('#test').inputmask('(99[9]) 99999-99999', { keepStatic: true});

Or you rewrite the mask as

$('#test').inputmask('(9(9|99)) 99999-99999')
