### ISSUE TITLE
Missing documentation on "negationSymbol" option

### ISSUE THREAD

**Issue by xantari** [RobinHerbots/jquery.inputmask#2625]
I found how to do this, but I had to dig through the sources and do some google searches to find it.

The documentation is missing this parameter: "negationSymbol".

Please add documentation about negationSymbol so other users know it exists.

I figured it out using it this way:

```js
    Inputmask("decimal", {
        radixPoint: ".",
        groupSeparator: ",",
        digits: 2,
        autoGroup: true,
        prefix: '$',
        negationSymbol: { front: '(', back: ')' }
    }).mask(".currency");
```

**Comment by RobinHerbots** [comment]
https://github.com/RobinHerbots/Inputmask/blob/5.x/README_numeric.md#negationsymbol
