### ISSUE TITLE
groupSeparator on el-input didn't work as expected

### ISSUE THREAD

**Issue by yuniit** [RobinHerbots/jquery.inputmask#2629]
every time groupSeparator appears cursor position return back to previous value
Here my [codepen](https://codepen.io/yuneath/pen/XWZxEzo)

vue@3.2.37
element-plus@2.2.5
inputmask@5.0.7

**Comment by RobinHerbots** [comment]
@yuniit ,

I guess it is some interference with the element-plus.

Adding the    noValuePatching: true option in the inputmask solves the issue.

Maybe you can also try without the element-plus, if that also works then we can investigate more to see why.

**Comment by yuniit** [comment]
@RobinHerbots 
Thanks for the fast response.
everything is working fine now with `noValuePatching: true`

**Comment by yuniit** [comment]
HI @RobinHerbots 
`autoValue` + `noValuePatching` make value reversed on focus.

https://user-images.githubusercontent.com/30621352/173319011-a5ae2f08-ac6f-406d-93b2-3496da9cf6fc.mov


please see [Codepen](https://codepen.io/yuneath/pen/qBxLXRB) 


So currently i'm using `computed` for unmaked value [Codepen](https://codepen.io/yuneath/pen/XWZxEzo)

**Comment by RobinHerbots** [comment]
@yuniit ,

Just fixed the reversing issue.  Have a try with 5.0.8-beta.25

**Comment by yuniit** [comment]
> 5.0.8-beta.25

I just run `npm install inputmask@next --save` but I got version `5.0.8-beta.17` instead of `5.0.8-beta.25`

I tried `npm install inputmask@5.0.8-beta.25 --save` and I got this error:
```
npm ERR! notarget No matching version found for inputmask@^5.0.8-beta.25.
```

Is version  `5.0.8-beta.25` available yet?

**Comment by RobinHerbots** [comment]
It is available now ;-)

**Comment by yuniit** [comment]
@RobinHerbots  Thank you for fixing the reversing issue.
but it seems like `autoUnmask` not working if `noValuePatching` is set to `true`

**Comment by RobinHerbots** [comment]
@yuniit ,

I think that is logical as the value property isn't altered.
Have a read at https://github.com/RobinHerbots/Inputmask#unmaskedvalue
