### ISSUE TITLE
Clear MaskText while typing

### ISSUE THREAD

**Issue by tiagompb** [RobinHerbots/jquery.inputmask#2638]
Hi,
Using the mask text in a input text and having these properties set:
clearMaskOnLostFocus: true
showMaskOnFocus: false
showMaskOnHover: false

I thought the mask would never be seen even while typing. The mask is always shown on focus if the character is not the first or if the input is still empty.

![image](https://user-images.githubusercontent.com/12599665/180193778-a2fc11c5-cff8-4854-b33a-ee913fdae351.png)

- Inputmask version: 5.0.0-beta.318

Thanks,
Tiago

**Comment by RobinHerbots** [comment]
@tiagompb , 

Use the jitmasking optrion.  (see readme)
