### ISSUE TITLE
Regex unicode categories cause RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Skipperwastaken** [RobinHerbots/jquery.inputmask#2639]
Unicode categories such as `\p{L}` or `\p{P}` cause `RangeError: Maximum call stack size exceeded` 
Tested on Chrome 103.0.5060.134 and Edge 103.0.1264.71

**Comment by MSergiu7** [comment]
I'm having the same issue using the regex: "[0-9]*" with greedy set to true. Greedy false seems to work fine.
It's working in 5.0.7-beta.17 but not working in latest version anymore. Tested on: https://jsfiddle.net/Sergiu_Morar/9xo7qr4L/12/

**Comment by RobinHerbots** [comment]
@Skipperwastaken ,

Support for unicode categories is added.
See v5.0.8-beta.41
