### ISSUE TITLE
Can`t input less than 1$ without  using keyboard arrows in alias: "currency" with decimals

### ISSUE THREAD

**Issue by Anton1921980** [RobinHerbots/jquery.inputmask#2640]
I think there must be possibility to input decimals on second mouse click,
disable focus on decimal separator on second click, it works so if I input some digit before decmals

https://user-images.githubusercontent.com/56801823/183105276-9d744e40-e8e1-4606-a000-c31d42c26191.mp4

"react": "^17.0.2",
 "inputmask": "^5.0.7",
 Windows 10, Chrome,

**Comment by RobinHerbots** [comment]
@Anton1921980 ,

Try typing:
- .02
- 0.02
- 1.02

or use the numericInput: true options and type

- 2
- 102

**Comment by RobinHerbots** [comment]
@Anton1921980 , 

Ofcourse you can also use https://github.com/RobinHerbots/Inputmask/blob/5.x/README.md#positioncaretonclick

**Comment by RobinHerbots** [comment]
alias: "currency",
        positionCaretOnClick: "none"

**Comment by RobinHerbots** [comment]
@Anton1921980 , 

Now that I have reread your issue, .... hmm yes, ...  this is already the case once you have typed something.  Maybe this should also work without the need to type something.  I will change that.

**Comment by RobinHerbots** [comment]
@Anton1921980 , 

Done!
