### ISSUE TITLE
error message: Cannot read properties of undefined (reading 'allowMinus')

### ISSUE THREAD

**Issue by WenSheng-tw** [RobinHerbots/jquery.inputmask#2642]
- HTML:

`< input type="text" id="ieFD_PKG" style="display: inline-block; width: 35px; height: 26px; z-index: 17; text-align: right; background: white; border-color: rgb(224, 224, 224);" name="ieFD_PKG" value="" spellcheck="false" inputmode="numeric" maxlength="2" >`

- JS code:
 `
$('#ieFD_PKG').inputmask({
	 regex: "^[0-9]{2}(\\.\\d{2})?$"
	,rightAlign: true
	,alias: 'integer'
	,allowMinus: false
	,min: 0
	,max: 99
});
`

type number '1' or '23' and other number,
and press keyboard 'backspace' many time.
chrome console is show: Cannot read properties of undefined (reading 'allowMinus')

I found solution:
line 1165:
  old code is:
 `
                                    return n.allowMinus && e === n.negationSymbol.back;
 `

 change to: 
 `
                                    if(typeof(n) == 'object'){
                                      return n.allowMinus && e === n.negationSymbol.back;
                                    }else{
                                      return false;
                                    }
`
and modify line 1160: 
old code is:
 `
                                    return n.allowMinus && ("-" === e || e === n.negationSymbol.front);
 `
change to:
 `
                                    if(typeof(n) == 'object'){
                                        return n.allowMinus && ("-" === e || e === n.negationSymbol.front);
                                    }else{
                                      return false;
                                    }
 `

- OS: Windows 10
- Browser: Chrome 105.0.5195.52
- Inputmask version: 5.7, 5.6....

**Comment by RobinHerbots** [comment]
@WenSheng-tw,

The isssue is fixed in version "5.0.8-beta.37"
