### ISSUE TITLE
Tab not moving to next field

### ISSUE THREAD

**Issue by jacoch** [RobinHerbots/jquery.inputmask#2644]
Hi

Thanks for that great plugin. Today, I updated the v4 I was using on a web site to the latest version 5. Unfortunately, I discovered that the TAB key cannot be used anymore to move between fields. Reverting to v4 fixed the problem. I tried it on the official demo page (https://robinherbots.github.io/Inputmask) and see the same problem. Keyboard layout is Swiss French (almost same as German one) if it plays any role.

Tested on Windows and MacOS, Firefox, Safari and Edge.

**Comment by RobinHerbots** [comment]
@jacoch ,
Fixed in Version: 5.0.8-beta.43

**Comment by kamilpinas** [comment]
> @jacoch , Fixed in Version: 5.0.8-beta.43

can u release this beta version? ;)
