### ISSUE TITLE
The leap year doesn't play well with `jitMasking` parameter

### ISSUE THREAD

**Issue by emrecamasuvi** [RobinHerbots/jquery.inputmask#2647]
Hi everyone 👋🏼  &nbsp;We've got an issue with the leap years

- With the parameter `jitMasking: true` when you begin to type `29.02` you can't continue typing `1980` 
- Adding `leapday: '29.02.'` didn't help as well
- Similar to #2453 (was supposed to be fixed by then but seems like re-broken)
- Inputmask version: v.5.0.7 (**doesn't work** with `5.0.8 beta versions` as well)
- https://jsfiddle.net/camasuvi/0m2nuLkr/2/

Thanks in advance!

**Comment by KaddieIII** [comment]
Hi, we have the same issue. It's not possible to enter an odd digit as the first digit of the year. 
- 29.02.2xxx, 29.02.4xxx, 29.02.6xxx and 29.02.8xxx work, but 
- 29.02.1xxx, 29.02.3xxx, 29.02.5xxx, 29.02.7xxx, 29.02.9xxx and 29.02.0xxx do not work. 
As the second digit I can only enter 0, 4 and 8. I think that comes from "every year, that can be devided by 400 is a leap year".

**Comment by KaddieIII** [comment]
Any updates regarding this topic so far? This is really urgent.

**Comment by KaddieIII** [comment]
Hey, do you have any updates on this topic? :) 

Thanks in advance

**Comment by RobinHerbots** [comment]
Hi @emrecamasuvi , @KaddieIII ,

The issue is solved in the current beta and also added to the unittests.
