### ISSUE TITLE
AltGr key Problem

### ISSUE THREAD

**Issue by qahef** [RobinHerbots/jquery.inputmask#2649]
When you press the AltGr key, the word "AltGraph" appears in the input field.
How do I fix this error bug?
I have a German Keyboard.

Kind regards.

**Comment by RobinHerbots** [comment]
@qahef , 

This is with the latest version right?
I will fix this asap.  It is due to the refactoring of the keyevents..

Can you give an example of the mask you used.


Thx for reporting.

**Comment by RobinHerbots** [comment]
@qahef ,

I already fixed the issue..  It is fixed on the next commit.  Maybe if there some other keys which behave the same you can let me know also.

Best regards,
Robin

**Comment by qahef** [comment]
yes with the latest version
here an example:
![image](https://user-images.githubusercontent.com/24733325/191113122-6c7ede2a-6ab8-417b-9d25-a0d55b781d19.png)

**Comment by qahef** [comment]
same with the Capslock key:
![image](https://user-images.githubusercontent.com/24733325/191113579-a2cb34f6-cc7a-4022-ad37-307fb9d245c8.png)
