### ISSUE TITLE
Reference error when server side rendering

### ISSUE THREAD

**Issue by splashdust** [RobinHerbots/jquery.inputmask#2661]
Everything works well when only running in the browser, but the following error prevents the application from starting up when rendering on the server side:

```
node_modules/inputmask/dist/inputmask.js:13
}(self, (function() {
^
ReferenceError: self is not defined
```

`self` is only availble in a browser context, so it fails on the server.

Inputmask version
`5.0.7`

**Comment by RobinHerbots** [comment]
Have a try with version  5.0.8-beta.47

**Comment by splashdust** [comment]
> Have a try with version 5.0.8-beta.47

Thank you for replying! I tried upgrading to `5.0.8-beta.47`, but am still getting the error:

```
inputmask.js:13
}(self || this, (function() {
  ^

ReferenceError: self is not defined
```

I see that it is now supposed to use `this` if `self` is falsy. However, since `self` is not defined at all in this context, the result is still a reference error.

The code would need to look something like this to work:
```javascript
}(typeof self !== 'undefined' ? self : this, (function() {
```

**Comment by splashdust** [comment]
Added a PR for a proposed solution: #2663

**Comment by RobinHerbots** [comment]
@splashdust , 

Thx !!!
