### ISSUE TITLE
(Japanese IME)Appear repeated number when bluring from the feild after entered 123 in Japanese IME

### ISSUE THREAD

**Issue by IsabellaGao12** [RobinHerbots/jquery.inputmask#2662]
now I use the `<input data-inputmask="'mask': '99999999999'" />` to get the effect of phone number, I entered 123 and then blur from this filed in Japanese IME, the double 123 can appear in the field. but if I just press the Enter from this field, that is fine.

inputMask version: 5.0.8-beta.47-0
Browser: Chrome

the attached file is my test screenshot

https://user-images.githubusercontent.com/101157677/199468495-8d15d292-8181-487d-b3b7-dd9ed5cfa992.mp4

**Comment by KathleenLu1** [comment]
@RobinHerbots  Could you please help check this issue?

**Comment by RobinHerbots** [comment]
Hi @IsabellaGao12 , @KathleenLu1 ,

I installed the simplefied chinese ime (Microsoft pinyin) and put the character on full width.
That seems to work just fine.

Maybe is it due to the IME.  Which do you use exactly?  How can I install it to have a try.

**Comment by KathleenLu1** [comment]
we used Japanese IME on windows system. Could you please help check it? Thanks!
In below link:
https://github.com/RobinHerbots/Inputmask/issues/1606
[wesleywong](https://github.com/wesleywong) Have same issue, but not found solution.
`Thanks for the reply. yeah, by this code i can type in full width character just that it will double up the character when i enter. e.g. "１" = "１１"`

**Comment by RobinHerbots** [comment]
@KathleenLu1 ,

Can you have a try with the latest version on github.  I made a fix for the double entry.

Best regards,
Robin

**Comment by IsabellaGao12** [comment]
@RobinHerbots 
Thanks for your help. I have tried the latest version, now the issue that mentioned in my description is fine, but when I input 0 by Japanese IME, can appear double 0, other numbers are fine but 0. Could you help to check this again? Thanks a lot. 
![double 0 issue](https://user-images.githubusercontent.com/101157677/200237603-cea83738-778b-47fc-bc74-9a2f37d2616a.gif)

**Comment by RobinHerbots** [comment]
Hi @IsabellaGao12 ,

I've submitted another fix.  Can you have a try.  (With enter you can confirm the composition.  )

**Comment by KathleenLu1** [comment]
> @KathleenLu1 ,
> 
> Can you have a try with the latest version on github. I made a fix for the double entry.
> 
> Best regards, Robin

Thank you so much! I'll have a try!

**Comment by IsabellaGao12** [comment]
Hi @RobinHerbots
Thank you for helping us. I have tested the latest version(5.0.8-beta.50), now the two issues I mentioned have been fixed, but I find another one issue that the value will be empty when I press the Enter key after input some numbers by Japanese IME as below test screenshot, actually this issue is fine in version(5.0.8-beta.49), Could you help to check this? Thank you very much!
![enter issue](https://user-images.githubusercontent.com/101157677/200983318-4387bc07-72fd-4966-a994-e650aff15675.gif)

**Comment by RobinHerbots** [comment]
@IsabellaGao12 ,

And when you select the value?

**Comment by IsabellaGao12** [comment]
> @IsabellaGao12 ,
> 
> And when you select the value?
@RobinHerbots 
for example, when I input 1234 by Japanese IME and then directly press Enter Key, the fields's content is cleared, the right should be keep the entered value.  (5.0.8-beta.50)

**Comment by RobinHerbots** [comment]
Can you do some debugging for me?

Before you press enter you put a breakpoint in the inputFallBackEvent function.

I would like to see the stacktrace and maybe you can step through and see what happens.

You will see something like  if (p !== d && (void 0 === e.inputType || "insertCompositionText" !== e.inputType)) {

What is the value of p, d and e.inputType

**Comment by IsabellaGao12** [comment]
@RobinHerbots
first screenshot: my operation steps: input 1 first, and then directly blur from this field by clicking blank area.
second screenshot:  input 1 first, and then press enter
![track](https://user-images.githubusercontent.com/101157677/201055929-af62c79f-1403-462a-8a32-4925de9814fb.gif)
![track2](https://user-images.githubusercontent.com/101157677/201055937-9c6f203f-db24-4764-8717-24f775c484e4.gif)

**Comment by RobinHerbots** [comment]
One more thing.

In the keypressevent function.

You will see at the end c.isComposing && (h.trigger("input"), c.isComposing = !1));

Is the input event triggered in case when typing enter.  (that's why I needed the stacktrace.)

**Comment by IsabellaGao12** [comment]
Hi @RobinHerbots
I tracked the code, the input event or change event cannot be triggered when I press the Enter first time, but I continue to press the Enter second time, the event can be triggered. so if I only press Enter key once and then blur, the field's value can be cleared, but if I press Enter key twice, the value is fine.

**Comment by RobinHerbots** [comment]
@IsabellaGao12 ,  @KathleenLu1 ,

Can you have a try with the latest version.  I created some kind of hack for the japanese ime.

**Comment by IsabellaGao12** [comment]
@RobinHerbots I will have a try with the latest version, Thank you very much for your help
