### ISSUE TITLE
Current mask character is selected in dates, which is announced twice by screen readers

### ISSUE THREAD

**Issue by tzbarkan** [RobinHerbots/jquery.inputmask#2664]
When typing in a field with a date mask, the current mask character is selected. This does not happen in other mask types. This causes the current mask character to be read on each keystroke multiple times. In the image below, you can see NVDA 2022.3.1 (latest version as of today) on Windows announcing 2 events for character selection of each placeholder/mask character. Additionally, NVDA announces the removal of the selection upon completion.

![image](https://user-images.githubusercontent.com/77458338/200353033-eba8f145-f2a4-4f11-b586-962de5d5ee95.png)

The problem is reproducible on the demo at https://robinherbots.github.io/Inputmask/ in Edge, Firefox, and Chrome. (Assuming it happens on other browsers, too).

Expected behavior would be that no characters are selected as the user types. Below is what NVDA does with a currency field on the same page:
![image](https://user-images.githubusercontent.com/77458338/200354806-a8d277ba-e258-42d6-918c-10142dab1d0e.png)

The rest of the masks behave as expected.

(Note: I have set NVDA to not read individual key strokes. So if a user did have that default option still on, they would have the date mask selection/deselection read in addition to each character they type.)

**Comment by RobinHerbots** [comment]
Hi @tzbarkan ,

I think adding the insertModeVisual: false option will bring some relief.

**Comment by tzbarkan** [comment]
That does fix it, thank you for the rapid response.

I defer to you on making a change to this behavior, but I would expect the default settings to behave the same for each field.

**Comment by RobinHerbots** [comment]
I changed the default behavior for the datetime alias.
