### ISSUE TITLE
If I use date_time alias with mask "HH:MM" I get "d_tetime" placeholder

### ISSUE THREAD

**Issue by giacomomasseron** [RobinHerbots/jquery.inputmask#2666]
Hi,  
If I use this code:

`Inputmask({alias: "datetime", inputFormat: "HH:MM"}).mask(document.querySelectorAll('.inputmask-time'));`

I get an input with value and placeholder set to the string "d_tetime" and I can not write on the input.

**Comment by RobinHerbots** [comment]
Can you give some more context.  WHich files did you reference/import?

**Comment by giacomomasseron** [comment]
Sure.  
I installed the package with npm, and I import it with this code:  

`import inputmask from "inputmask/lib/inputmask";`

**Comment by RobinHerbots** [comment]
Try to import like

import inputmask from "inputmask";

**Comment by giacomomasseron** [comment]
Same behaviour.

I noticed the problem occurs when the mouse goes over the input masked.  
Before that, the input does have "HH:mm" as placeholder. As soon as I go with mouse over the input, the placeholder changes to "d_te_time"

**Comment by RobinHerbots** [comment]
Hmm, can you create an example on codepen or another platform.

**Comment by giacomomasseron** [comment]
I solved.  
I effectively (I thought I was using it but it wasn't true) used this:

`import inputmask from "inputmask";`

and it works. Thanks for the help, I close the issue.
