### ISSUE TITLE
Remove Inputmask placeholder on focus

### ISSUE THREAD

**Issue by SDeepesh** [RobinHerbots/jquery.inputmask#2670]
On focus I am getting 0 by default on "inputMask": "decimal". Is there a way to remove that on focus?

![Screenshot 2022-11-22 181817 (1)](https://user-images.githubusercontent.com/63853806/204458087-045a74c6-a86e-4e8c-874b-90302751882a.png)

![Screenshot 2022-11-29 121412](https://user-images.githubusercontent.com/63853806/204457922-3a793005-2bee-4c23-8bd4-91f5e8fa9d5a.png)

https://codesandbox.io/s/sweet-worker-xpn6zh

**Comment by RobinHerbots** [comment]
@SDeepesh ,

Add the   placeholder:"" option

**Comment by SDeepesh** [comment]
![image](https://user-images.githubusercontent.com/63853806/206629097-a73226ad-5be3-4da6-a9ac-5364085ac7c1.png)
Its still the same after adding placeholder https://codesandbox.io/s/sharp-zeh-z6t6y8

**Comment by RobinHerbots** [comment]
@SDeepesh ,

This only works with a newer version.

**Comment by SDeepesh** [comment]
I have updated the version to 5.0.7 and still didn't work

**Comment by SDeepesh** [comment]
Hi any update on this one?

**Comment by SDeepesh** [comment]
![image](https://user-images.githubusercontent.com/63853806/212851139-1311bc7c-7175-49ac-8a83-4c58e495e652.png)

https://codesandbox.io/s/sharp-zeh-z6t6y8?file=/package.json

**Comment by RobinHerbots** [comment]
Hi @SDeepesh ,

I see that the inputmask in the example is wrapped by surveyjs which comes with version 4.0.7.
I looked a bit at their code and they do not map the placeholder when using the decimal mask, but they do for the currency mask.
So instead use the currency mask and make the following changes in the SurveyComponents.jsx.  

```
const inputmask = SurveyCore.CustomWidgetCollection.Instance.getCustomWidgetByName(
  "maskedit"
);
inputmask.widgetJson.numericGroupSeparator = " ";
inputmask.widgetJson.numericPlaceholder = "";
inputmask.widgetJson.numericDigitsOptional = true;
```
In the input.json you set the currency mask.
```
export const json = {
  elements: [
    {
      type: "text",
      placeholder: "",
      inputMask: "currency",
      showMaskOnHover: false,
      name: "decimal",
      title: "Decimal:"
    }
  ]
};
```


Hope this helps.

Best regards,
Robin

**Comment by SDeepesh** [comment]
Hi @RobinHerbots thanks for the message, it looks like the solution is working :)

Thank you
