### ISSUE TITLE
Is Inputmask v5.0.7 impacted by jQuery UI v1.9-1.10's removal of item.autocomplete 

### ISSUE THREAD

**Issue by rebrads** [RobinHerbots/jquery.inputmask#2675]
Line#2284 of Imputmask v5.0.7 includes i.autocomplete() as a parameter at the end of it.

I noticed the migration guide for jQuery UI v1.9 mentions "Non-namespaced widget instances and item.autocomplete will be removed in 1.10".  Will Inputmask v5.0.7+ be impacted by that change in jQuery UI?

Reference: https://jqueryui.com/upgrade-guide/1.9/

**Comment by RobinHerbots** [comment]
@rebrads ,
This is the HTML attribute: autocomplete.  So there will be no impact
