### ISSUE TITLE
Unidentified in url mask on mobile

### ISSUE THREAD

**Issue by aolko** [RobinHerbots/jquery.inputmask#2676]
- instead of working normally on mobile input shows `Unidentifiedtp://` and more `unidentified` per tap
- [codepen](https://codepen.io/aolko/full/NWBKqBp)
![](https://i.ibb.co/hZ6jPHv/Screenshot-20221216-160255-2.png)
- OS: Android 12
- Chrome latest
- 5.0.8.beta.47

**Comment by RobinHerbots** [comment]
I will publish a newer beta

**Comment by RobinHerbots** [comment]
@aolko ,

Can you have a try with version 5.0.8-beta.70

**Comment by aolko** [comment]
works as expected, but allows erasing invisible characters at `http://`

**Comment by RobinHerbots** [comment]
What do you mean exactly by deleting invisible chars at ...

**Comment by aolko** [comment]
keep tapping `⌫` when you erased your text with only `http://` left

**Comment by RobinHerbots** [comment]
Ok that's because you can also type in anothr protocol like ftp
