### ISSUE TITLE
Blue selection on DateTime mask

### ISSUE THREAD

**Issue by mrleblanc101** [RobinHerbots/jquery.inputmask#2679]
Why does this show a blue text selection on DateTime input mask instead of a regular cursor ?
Can this overriden ?
![Capture d’écran, le 2022-12-23 à 11 40 12](https://user-images.githubusercontent.com/17392251/209369302-f1d608bf-7ecc-41a4-a104-fa24925c72ce.png)

The demo page does not have this behavior.
![Capture d’écran, le 2022-12-23 à 11 38 53](https://user-images.githubusercontent.com/17392251/209369067-65a0ace5-c695-4b26-ac99-f092f8f13d84.png)

Here is my code:
```
new Inputmask("datetime", {
    inputFormat: "HH:MM",
    clearMaskOnLostFocus: false,
}).mask(timeInput);
```

**Comment by RobinHerbots** [comment]
@mrleblanc101,

Add   insertModeVisual: false, option
In the latest version this is the default

**Comment by mrleblanc101** [comment]
Oh yeah I ended up figuring it out a few day ago. Completely forgot to come and close this issue. Thanks !
