### ISSUE TITLE
Change Event fired on Blur even if value has not changed

### ISSUE THREAD

**Issue by melloware** [RobinHerbots/jquery.inputmask#2691]
# Describe the bug

The line right here: https://github.com/RobinHerbots/Inputmask/blob/5.x/lib/eventhandlers.js#L456

Always fires Change even if the value has not changed. So just clicking into the field and clicking out fires the change event.

Original Report: https://github.com/primefaces/primefaces/issues/9819

CodePen: https://codepen.io/melloware/pen/rNZxXrN

- **OS:** ALL
- **Browser** ALL 
- **Inputmask version =** 5.8

**Comment by melloware** [comment]
I believe the bug is in the focus event is using the "masked" value and not the original value of the input.

![image](https://user-images.githubusercontent.com/4399574/220686281-db14cce1-03eb-45e7-9752-a82d64a4440a.png)

**Comment by RobinHerbots** [comment]
@melloware ,

I'm working on a fix.   The PR may work in some cases, but not always.

**Comment by melloware** [comment]
Thank you.
