### ISSUE TITLE
Changelog between 5.0.7 and 5.0.8

### ISSUE THREAD

**Issue by chkpnt** [RobinHerbots/jquery.inputmask#2696]
The change in the version number suggest only minor changes. But as the diff between 5.0.7 and 5.0.8 [is huge](https://github.com/RobinHerbots/Inputmask/compare/5.0.7...5.0.8) (79 commits, 52,410 additions and 10,123 deletions), I'm unsure if there's anything I should know?

**Comment by chkpnt** [comment]
Oh, I've found the changelog in a subdirectory: https://github.com/RobinHerbots/Inputmask/blob/5.x/inputmask-pages/src/assets/Changelog.md

I suggest to move it to the project root under CHANGELOG.md, so that tools like Renovate can make use of it. Currently, Renovate shows updates of `inputmask` as follows:

![grafik](https://user-images.githubusercontent.com/1956979/227489701-72cb2c99-42f3-4ed0-b479-a45bfa1c214b.png)

**Comment by RobinHerbots** [comment]
@chkpnt,

You can see the changes here https://robinherbots.github.io/Inputmask/#/changelog

There are no breaking changes.  But I can agree that it is more then a patch :-)
