### ISSUE TITLE
Use in ReactJs

### ISSUE THREAD

**Issue by renerlemes** [RobinHerbots/jquery.inputmask#2703]
Is possible to use this lib in React Web? If yes, is possible to show an example?

**Comment by RobinHerbots** [comment]
@renerlemes , 

Yes you can.  Maybe you can have a look at  https://github.com/RobinHerbots/Inputmask/blob/5.x/inputmask-pages/src/Components/DemoMask/DemoMask.js

Or maybe someoneelse has a better example proposal?

**Comment by renerlemes** [comment]
@RobinHerbots I can create the component, but when I use it, I don't make any mask. Do you have any other examples?

**Comment by renerlemes** [comment]
@RobinHerbots I managed to use it, but when I go to use it passing a string array in the mask property, it doesn't work as it should. Only apply the mask to the first mask of the array

**Comment by renerlemes** [comment]
@RobinHerbots take a look at this example:
https://codesandbox.io/s/ant-design-inputmask-77wund

See if you can simulate the following errors:

- If I type **123** it will return **123.** and it's correct, but if I try to delete it, nothing happens.
- If I type **1234** it will return **123.4** and it's correct, but if I try to delete it, nothing happens.
- If I type **12345678901** it will return **123.456.789-01** and it's correct, however if I type one more character, it doesn't change the mask.

Could it be something from Ant Design's Input component?

I also realized that if I don't return the value with the mask to the input, just viewing it in the console, the mask erases and changes automatically between the two masks.

But still continue with the following error:
- If I type **1234**, it will return **123.4** and it is correct, however when I delete character 4, it is not deleting the **.** to stay only **123**

**Comment by eduardoborges** [comment]
hey @renerlemes this library implements inputmask with react fro u:

https://github.com/eduardoborges/use-mask-input/

**Comment by RobinHerbots** [comment]
@renerlemes ,

Is this solved?  Your example isn't accessible enymore.

**Comment by renerlemes** [comment]
@RobinHerbots It is now accessible again. You have inputmask version 5.0.0, if you update to 5.0.8 you will see the problem

**Comment by RobinHerbots** [comment]
```
import { useState, useRef, useEffect } from "react";
import { Form, Input, Typography } from "antd";

import Inputmask from "inputmask";

export default function App() {
  const [value, setValue] = useState("");
  const [form] = Form.useForm();
  const inputRef = useRef();

  useEffect(() => {
    Inputmask({
      mask: ["999.999.999-99", "99.999.999/9999-99"],
      jitMasking: true
    }).mask("replacemewithinputref");
  }, []);

  const handleChange = (e) => {
    setValue(e.target.value);
  };
  return (
    <Form form={form}>
      <Form.Item label="No Mask" name="CpfCnpj" rules={[{ required: true }]}>
        <Input id="replacemewithinputref" inputRef={inputRef} onChange={handleChange} />
      </Form.Item>
      <Typography.Text>Mask: {value}</Typography.Text>
    </Form>
  );
}
```

This will do, ....

The problem with your example is that the jitMasking will format 123 to 123., .... so if you delete the . you will get the same value as before.  

The question is, should the jitMasking behavior render the dot beforehand or only after typing the 4 in this case.
I guess after typing 4 except when the dot would be the last character of the mask.

**Comment by renerlemes** [comment]
It worked now! Thanks
