### ISSUE TITLE
Alternator not working in 5.0.9-beta.6

### ISSUE THREAD

**Issue by fanste** [RobinHerbots/jquery.inputmask#2711]
JSFiddle: https://jsfiddle.net/z3wgjdhf/1/

Seems to be broken since 5.0.9-beta.3 (commit 377a8695220b28b17bb4fd0554bbbe83b96288e5). Version 5.0.9-beta.1 (commit 32dec4abd9260e484d7d95c30d8893b47b7b211f) is working.

Mask is configured with 
```javascript
Inputmask({
    // complex alternator mask as optional is working as expected
    mask: '(*-******)|(*-******-**)|(*-******-**-**)|(*-******-**-**-**)|(*-******-**-**-**-**)|(*-******-**-**-**-**-***)',
    clearIncomplete: true,
    keepStatic: true
})
```

If you type in 7 chars (first mask), everything is just fine.
![image](https://github.com/RobinHerbots/Inputmask/assets/3531183/a0d4945b-92d2-4b92-9a7f-8614724c836e)

But if you add one more char to start the second mask (here an `a`), the mask gets messed up.
![image](https://github.com/RobinHerbots/Inputmask/assets/3531183/07b08268-a754-45ea-bbb5-736356268160)
It directly jumps to the third mask and even removes some digits.

**Comment by fanste** [comment]
Additional observation with `beta.3`:
If you just enter `1-1` and press backspace, the result is `-1` instead of `1-`.

This is also working with `beta.1`

**Comment by luco** [comment]
Same here!

**Comment by RobinHerbots** [comment]
Can you retry with 5.0.9-beta.7

**Comment by fanste** [comment]
This bug seems to be fixed.

Thanks for the fast response.
