### ISSUE TITLE
State of alternator not reset with `clearIncomplete = true`

### ISSUE THREAD

**Issue by fanste** [RobinHerbots/jquery.inputmask#2712]
Tested using 5.0.9-beta.6
JSFiddle: https://jsfiddle.net/mxLs0eqj/2/

Input is configured with
```javascript
Inputmask({
    // complex alternator mask as optional is working as expected
    mask: '(*-******)|(*-******-**)|(*-******-**-**)|(*-******-**-**-**)|(*-******-**-**-**-**)|(*-******-**-**-**-**-***)',
    clearIncomplete: true,
    keepStatic: true
})
```

If you type in `12345678` to get to the second mask and then leave the input, the input is cleared, Thats OK.
![image](https://github.com/RobinHerbots/Inputmask/assets/3531183/bafb6f1a-4385-4a14-b3bd-2c2f1aff3b9e)

But then you can't enter a value matching the first mask until backspace is pressed. The internal state only then seems to be cleared as well and the input still expectes a value matching the second (or higher) mask. A value matching the first mask is always rejected and cleared again.
![image](https://github.com/RobinHerbots/Inputmask/assets/3531183/05813259-19aa-4f51-af40-25c8f46b6510).

**Comment by fanste** [comment]
A not so nice workaround is to add:
```javascript
, onincomplete: function() {
    this.inputmask.setValue('');
}
```

**Comment by RobinHerbots** [comment]
@fanste , 

I pushed 5.0.9-beta.7

**Comment by fanste** [comment]
Same behavior as before. The changes in `beta.7` do not fix this issue.

**Comment by RobinHerbots** [comment]
Hmm, isn't this a caching issue?

**Comment by RobinHerbots** [comment]
https://jsfiddle.net/bnom37d0/1/

**Comment by fanste** [comment]
No, unfortunately it isn't a caching issue. I just tried in on your jsfiddle and even reloaded the page with Strg+F5.

- Hover the field. Placeholder `_-______` is shown
- Focus the field. Placeholder `_-______` is shown
- Enter `1234567`
- Blur the field, value is accepted.
- Add `8` to the previous sequence
- Blur the field, value is cleared.
- Hover the field. Placeholder `_-______` is shown
- Focus the field. Placeholder `_-______-__` is shown
- Enter `1234567`
- Blur the field, value is cleared
- Focus the field again (`_-______-__` is still displayed)
- Press backspace, placeholder changes to `_-______`.
- Enter `1234567`
- Blur the field, value is accepted

**Comment by RobinHerbots** [comment]
@fanste ,

You were right.  I pushed version 5.0.9-beta.9 which should fix it.  Can you have a try.

**Comment by fanste** [comment]
Bug is fixed with the new version. Thanks!
