### ISSUE TITLE
Number input started from last decimal place

### ISSUE THREAD

**Issue by Herald85** [RobinHerbots/jquery.inputmask#2716]
Would it be please possible to add functionality to start input from the last decimal place? E.g. mask has 2 decimal places, so when you type 1 it shows 0.01, when you type 2 it shows 0.12, with 3 it shows 1.23 and so on. Or is such possibility already there? I was not able to find any setting related to that.

**Comment by RobinHerbots** [comment]
Add the numericInput: true option
