### ISSUE TITLE
"NumLock", "ScrollLock" strings as input value while "A" mask using.

### ISSUE THREAD

**Issue by egorvdovenko** [RobinHerbots/jquery.inputmask#2720]
If we use the mask "A" (or any alphabet regex), then a strange behavior occurs when trying to activate/deactivate NumLock/ScrollLock modes. The "NumLock", "ScrollLock" strings are used as input values.

https://codepen.io/egorsergeevichw/pen/abQpBGR

I also noticed that the problem appeared in the package version 5.0.8, and the previous one does not have it.

**Comment by AntonDemushkin** [comment]
Hi @egorvdovenko! I have the same issue. Did you find a solution?

**Comment by RobinHerbots** [comment]
@egorvdovenko , @fremail ,

The issue is fixed in  5.0.9-beta.18

**Comment by egorvdovenko** [comment]
@RobinHerbots many thanks! So, when will it be published (as I see the current @next version is 5.0.8-beta.17)?

**Comment by RobinHerbots** [comment]
Done
