### ISSUE TITLE
dd.mm.yyyy can't enter a day greater than the 9

### ISSUE THREAD

**Issue by melloware** [RobinHerbots/jquery.inputmask#2723]
# Describe the bug

1. Enter 05.05.2023
2. Leave the input field
3. Put the caret at the very beginning of the input field
4. Press 3 (nothing will happen JS Error).
5. Press 2 (Date will change to 20.02.22__)

Original Report: https://github.com/primefaces/primefaces/issues/10312

CodePen: https://codepen.io/melloware/pen/rNZxXrN

- **OS:** ALL
- **Browser** ALL 
- **Inputmask version =** 5.8

**Comment by RobinHerbots** [comment]
Hi @melloware ,

This issue should be fixed in the latest beta version.

**Comment by melloware** [comment]
OK testing it out I am getting this error "Uncaught InternalError: too much recursion"

At this block of code
```js
 mm: [ "0[1-9]|1[012]", function(e) {
                        var t = e ? parseInt(e) : 0;
                        return t > 0 && t--, Date.prototype.setMonth.call(this, t);
                    }
```

**Comment by RobinHerbots** [comment]
@melloware ,

Hmm strange, can you provide the exact steps to get this.

**Comment by RobinHerbots** [comment]
Ok, 

I can reproduce the issue.  I will investigate it.

**Comment by melloware** [comment]
OK good.  I just grabbed your latest BETA and then tried to type "3" in a date that was "05/05/2023" after placing the cursor in the first spot.  When I press 3 I see that overflow.

**Comment by RobinHerbots** [comment]
There is new beta available.

Have a try!

**Comment by melloware** [comment]
OK I am able to take "05-08-2023` and type in "21" so it makes it "21-08-2023" but it wont let me type "30" for August 30th. The "3" is blocked?

**Comment by RobinHerbots** [comment]
I cannot reproduce this.

Can you reproduce it on the demo page? Or give the exact mask with option and a step sequence to reproduce

**Comment by melloware** [comment]
Is there any way to update my CodePen to point at your BETA version? https://codepen.io/melloware/pen/rNZxXrN  Can I just point to the GitHub URL directly?  I can't seem to get it work in CodePen.

**Comment by RobinHerbots** [comment]
Yes, with

https://rawgit.com/RobinHerbots/Inputmask/5.x/dist/inputmask.js

**Comment by melloware** [comment]
You are right the Codepen is working: https://codepen.io/melloware/pen/XWyOLav

Let me investigate further.

**Comment by melloware** [comment]
Confirmed its working. Wonder if I just needed to CTRL+F5 thanks for the fix!

**Comment by melloware** [comment]
I did open a new issue that my Integration Tests caught though with this update to 5.9.-30.  https://github.com/RobinHerbots/Inputmask/issues/2727
