### ISSUE TITLE
Input freezes after changing decimal value symbol twice

### ISSUE THREAD

**Issue by Pomierski** [RobinHerbots/jquery.inputmask#2731]
- Describe the bug
If we enter decimal value and change symbol twice using minus key, input freezes until we change our cursor position or select whole value. It's not possible to add or delete numbers.
- Add a link to a codepen, jsfiddle or other example page which shows the problem
https://robinherbots.github.io/Inputmask/#/demo (decimal)
- OS: Ubuntu 22.04.2 LTS
- Browser: Chrome 115.0.5790.110
- Inputmask version: v5.0.8

**Comment by embargiel** [comment]
@RobinHerbots Can I ask for a response here? This is very problematic for our project and also occurs in the latest beta

**Comment by RobinHerbots** [comment]
@embargiel ,

I will look into it.

**Comment by RobinHerbots** [comment]
Can you provide some more info  how to reproduce.

**Comment by Pomierski** [comment]
@RobinHerbots 
1. Go to https://robinherbots.github.io/Inputmask/#/demo
2. In "Decimal" input type `, 5 - - -`. It should be -0,5
3. Try to change value

https://github.com/RobinHerbots/Inputmask/assets/70658299/2f40b946-278a-4a14-9570-b3633910fbf9

**Comment by skrasnoyarov** [comment]
@RobinHerbots Hi, I also noticed that when entering a large number of digits after the decimal point, the text field starts to lag terribly

**Comment by RobinHerbots** [comment]
@skrasnoyarov,

The lag should be fixed with the latest beta

**Comment by RobinHerbots** [comment]
@Pomierski ,

The latest beta 71 should fix the issue.
