### ISSUE TITLE
Remove unused mask

### ISSUE THREAD

**Issue by SiKth** [RobinHerbots/jquery.inputmask#2734]
I can find this option in the documentation but it seams like a usable function.

I have a limit on 10 characters but when I fill in 3, the rest of the _ stays. Is there any way to remove or just hide the rest of the 7 mask characters?

Thanks, Fredrik

**Comment by RobinHerbots** [comment]
@SiKth ,

You need to make them optional.

```
Inputmask("*{0,10}").mask("#test1");
or
Inputmask("*{0,10}",
		{
			greedy: true
        }).mask("#test1");
```

**Comment by SiKth** [comment]
Hi,
I have been trying this for some time now without success. I am just trying to allow a max number of any characters to be entered, but any number below that is OK, with _ as placeholder and then that the rest of placeholders to disappear on blur. Here is my code, and as you can see the max number of characters in filled in by a variable. The only thing that does not work is that the _ stays if I fill in for example 4 out or max 10.

`<input type="text" id="tryck1" name="tryck1" class="inputfield-custom hej" data-inputmask-mask="[*]" data-inputmask-greedy="true" data-inputmask-placeholder="_" data-inputmask-repeat="' . get_field('number_of_char') .'" data-inputmask-clearMaskOnLostFocus="true" data-inputmask-clearIncomplete="false" data-inputmask-removeMaskOnSubmit="true" data-inputmask-autoUnmask="true" />`
