### ISSUE TITLE
When user press Ctrl+Alt / Alt+Ctrl key in the field, Can input characters with restricted formatting

### ISSUE THREAD

**Issue by yuyu668668** [RobinHerbots/jquery.inputmask#2736]
- Describe the bug
- https://robinherbots.github.io/Inputmask/#/demo
- 
![1693982205377](https://github.com/RobinHerbots/Inputmask/assets/30565249/8a4abdf5-0d8f-4ae5-b6a1-dae5ed7beb66)

**Comment by RobinHerbots** [comment]
@yuyu668668 ,

The issue is fixed in v 5.0.9-beta.32
