### ISSUE TITLE
attribute placeholder does not allow to set leap year

### ISSUE THREAD

**Issue by stagnofran** [RobinHerbots/jquery.inputmask#2740]
- When you configure the placeholder attribute the leap year stops working, I leave you a codepen where the error is reproduced.
try deleting the placeholder attribute and it will work correctly.  
test year 02/29/1984
- https://codesandbox.io/s/momentjs-playground-forked-9jfz6t?file=/src/index.js
- OS: Windows 11 
- Browser: Chrome
-  in all of them and in the last one as well

**Comment by stagnofran** [comment]
@RobinHerbots Hi! did you know about this bug?

**Comment by RobinHerbots** [comment]
Hi @stagnofran ,

Just use a newer version.

**Comment by stagnofran** [comment]
The fix is from 5.0.6, and in that version changes the entire structure of the node_modules folder.
when I run npm run start it tells me
inputmask/dist/jquery.inputmask.bundle.js doesn't exist
I look for it in node_modules and indeed it does not exist.

 @RobinHerbots

**Comment by RobinHerbots** [comment]
Just use jquery.inputmask.js or inputmask.js from the dist folder.  Thé
files are renamed.

BR,
Robin

Op ma 25 sep. 2023 23:34 schreef fran ***@***.***>:

**Comment by stagnofran** [comment]
try importing it like this
import Inputmask from 'inputmask/dist/inputmask';
also like this
import Inputmask from 'inputmask/dist/jquery.inputmask';
and also like this
import Inputmask from 'inputmask/dist/inputmask.es6';

and I always get this error

Module not found: Error: Package path ./dist/jquery.inputmask.bundle is not exported from package

@RobinHerbots

**Comment by RobinHerbots** [comment]
Can you share your package.json?

Op di 26 sep. 2023 21:00 schreef fran ***@***.***>:

**Comment by stagnofran** [comment]
this is my package.json 
`{
    "name": "@presentation/components",
    "version": "1.0.0",
    "description": "",
    "scripts": {
        "build:rollup": "rollup -c",
        "start:rollup": "rollup -c -w"
    },
    "author": "stagnfran",
    "dependencies": {
        "@tadashi/currency": "3.2.0",
        "chardet": "1.3.0",
        "chart.js": "2.9.4",
        "chartjs-plugin-datalabels": "0.7.0",
        "clockpicker": "0.0.7",
        "datatables.net": "1.10.21",
        "datatables.net-buttons": "1.6.5",
        "datatables.net-buttons-dt": "1.6.5",
        "datatables.net-dt": "1.10.21",
        "daterangepicker": "3.1.0",
        "dayjs": "^1.11.5",
        "eventemitter3": "4.0.7",
        "hacktimer": "^1.1.3",
        "imask": "6.0.5",
        "inputmask": "^5.0.9-beta.32",
        "jquery": "3.6.1",
        "jszip": "3.5.0",
        "lodash-es": "4.17.21",
        "mark.js": "8.11.1",
        "moment": "2.29.4",
        "pdfmake": "0.1.68",
        "rxjs": "7.5.5",
        "select2": "4.0.13",
        "string-hash": "1.1.3",
        "tippy.js": "6.2.7",
        "ui-contextmenu": "1.18.1"
    },
    "devDependencies": {
        "@babel/plugin-transform-runtime": "^7.19.6",
        "@babel/preset-typescript": "^7.18.6",
        "@rollup/plugin-babel": "^6.0.2",
        "@rollup/plugin-commonjs": "^23.0.2",
        "@rollup/plugin-node-resolve": "^15.0.1",
        "@rollup/plugin-typescript": "^9.0.2",
        "@rollup/plugin-url": "^8.0.1",
        "@testing-library/dom": "8.11.0",
        "@testing-library/user-event": "13.5.0",
        "jest-axe": "5.0.1",
        "jest-fetch-mock": "^3.0.3",
        "rollup": "^2.79.1",
        "rollup-plugin-visualizer": "4.2.0",
        "typescript": "4.9.5"
    }
}
`

and this is the package.json of your library 

`{
  "_from": "inputmask@next",
  "_id": "inputmask@5.0.9-beta.32",
  "_inBundle": false,
  "_integrity": "sha512-X4WxSCPTaLAnuVDyEt2WLa9mP56OQpZgJSg0YEPrmy7HMGxlbCr4tkut7TbPO+nSBDF1RXK603ZxB6bWLsS9uQ==",
  "_location": "/inputmask",
  "_phantomChildren": {},
  "_requested": {
    "type": "tag",
    "registry": true,
    "raw": "inputmask@next",
    "name": "inputmask",
    "escapedName": "inputmask",
    "rawSpec": "next",
    "saveSpec": null,
    "fetchSpec": "next"
  },
  "_requiredBy": [
    "#USER",
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/inputmask/-/inputmask-5.0.9-beta.32.tgz",
  "_shasum": "03c326662e8ba0fd872be366e5c27d898ba1ee20",
  "_spec": "inputmask@next",
  "_where": "/home/fran/veritran/webfly/frontend/packages/presentation-components",
  "author": {
    "name": "Robin Herbots",
    "url": "https://github.com/RobinHerbots"
  },
  "bugs": {
    "url": "https://github.com/RobinHerbots/Inputmask/issues"
  },
  "bundleDependencies": false,
  "deprecated": false,
  "description": "Inputmask is a javascript library which creates an input mask.  Inputmask can run against vanilla javascript, jQuery and jqlite.",
  "devDependencies": {
    "@babel/core": "^7.22.9",
    "@babel/plugin-transform-modules-commonjs": "^7.22.5",
    "@babel/preset-env": "^7.22.9",
    "@babel/preset-typescript": "^7.22.5",
    "@robinherbots/grunt-available-tasks": "^0.6.4",
    "@robinherbots/grunt-nuget": "^0.3.3",
    "babel-loader": "^9.1.3",
    "grunt": "^1.6.1",
    "grunt-bump": "^0.8.0",
    "grunt-contrib-clean": "^2.0.1",
    "grunt-contrib-copy": "^1.0.0",
    "grunt-eslint": "^24.3.0",
    "grunt-karma": "^4.0.2",
    "grunt-release": "^0.14.0",
    "grunt-webpack": "^6.0.0",
    "jquery": "^3.7.0",
    "karma": "^6.4.2",
    "karma-browserstack-launcher": "^1.6.0",
    "karma-chrome-launcher": "^3.2.0",
    "karma-qunit": "^4.1.2",
    "load-grunt-tasks": "^5.1.0",
    "lodash": "^4.17.21",
    "qunit": "^2.19.4",
    "webpack": "^5.88.2",
    "webpack-cli": "^5.1.4"
  },
  "exports": {
    ".": "./dist/inputmask.js",
    "./dist/*.js": "./dist/*.js",
    "./lib/*.js": "./lib/*.js",
    "./micromasks/*.js": "./micromasks/*.js"
  },
  "files": [
    "bundle.js",
    "Changelog.md",
    "dist/",
    "lib/",
    "micromasks/"
  ],
  "homepage": "https://github.com/RobinHerbots/Inputmask",
  "keywords": [
    "form",
    "input",
    "inputmask",
    "jquery",
    "jquery-plugin",
    "mask",
    "plugins"
  ],
  "license": "MIT",
  "main": "dist/inputmask.js",
  "name": "inputmask",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/RobinHerbots/Inputmask.git"
  },
  "scripts": {
    "jquery": "webpack --progress --watch --config-name jquery --config webpack.config.js",
    "start": "webpack --progress --watch --config-name main --config webpack.config.js",
    "test": "grunt validate"
  },
  "version": "5.0.9-beta.32"
}
`

**Comment by RobinHerbots** [comment]
Hmm, strange.

You did an npm i.

When you look into the node_modules/inputmask
Do you see something like:

![image](https://github.com/RobinHerbots/Inputmask/assets/318447/23bc036d-ed2f-4e6b-8f43-440b81e0c44f)

Can you replicate the issue in a codepen?

**Comment by stagnofran** [comment]
yes i did npm i and i see exactly that folder structure

I tried to replicate it in codepen but I could not.

it is strange that it keeps trying to access a file that does not exist since we are not calling it at any time. 

@RobinHerbots

**Comment by RobinHerbots** [comment]
@stagnofran ,

Maybe something in your webpack.config?

**Comment by stagnofran** [comment]
I solved it, there was another file that was importing the library from the absolute path and it was old.

Thank you very much for everything!
