### ISSUE TITLE
Unicode categories such as \p{P} or \p{S} does not work in `regexp` property

### ISSUE THREAD

**Issue by artuska** [RobinHerbots/jquery.inputmask#2741]
Unicode categories with the slash sign converts to the double slash and `regexp` become corrupred after the `createMask` function.

So, if i pass
`regex: '[\p{P}\p{S}]*'`
to the `createMask` function
and then `console.log` function result
i got
`regex: "[\\p{P}\\p{S}]*"`

And now i'm able to enter in the `inputmask` input only `p`, `P` and `S` characters.

**Comment by RobinHerbots** [comment]
@artuska ,

Can you elaborate a bit.  

It is not quiet clear what you mean.

**Comment by RobinHerbots** [comment]
Nevermind, I know what you mean.

I will see how to fix this.

**Comment by RobinHerbots** [comment]
@artuska ,

The issue is fixed but I need to push a new build.  Will do that soon.

**Comment by RobinHerbots** [comment]
Have a try with the latest beta version on npm
5.0.9-beta.33
