### ISSUE TITLE
Remove unused mask - Take2

### ISSUE THREAD

**Issue by SiKth** [RobinHerbots/jquery.inputmask#2748]
I have not yet solved this issue, please advice earlier issue below. Previous issue was #2734.

I have been trying this for some time now without success. I am just trying to allow a max number of any characters to be entered, but any number below that is OK, with _ as placeholder and then that the rest of placeholders to disappear on blur. Here is my code, and as you can see the max number of characters in filled in by a variable. The only thing that does not work is that the _ stays if I fill in for example 4 out or max 10.

`<input type="text" id="tryck1" name="tryck1" class="inputfield-custom hej" data-inputmask-mask="[*]" data-inputmask-greedy="true" data-inputmask-placeholder="_" data-inputmask-repeat="' . get_field('number_of_char') .'" data-inputmask-clearMaskOnLostFocus="true" data-inputmask-clearIncomplete="false" data-inputmask-removeMaskOnSubmit="true" data-inputmask-autoUnmask="true" />`

_Originally posted by @SiKth in https://github.com/RobinHerbots/Inputmask/issues/2734#issuecomment-1751429503_

**Comment by RobinHerbots** [comment]
@SiKth, 

I'm working on it.

**Comment by RobinHerbots** [comment]
@SiKth ,

Have a try with version 5.0.9-beta.37

**Comment by SiKth** [comment]
Works great, thanks!
