### ISSUE TITLE
Alias with datetime and long months is not working properly

### ISSUE THREAD

**Issue by stsrki** [RobinHerbots/jquery.inputmask#2751]
I'm not sure if this is a bug or if I am missing something.

I have a simple mask with the following options.

```js
picker.inputMask = new Inputmask({
    alias: "datetime",
    inputFormat: "dd.mmmm.yyyy"
});

picker.inputMask.mask(picker.altInput);
```

The input is rendered as following

![image](https://github.com/RobinHerbots/Inputmask/assets/900302/ab770058-9358-43a0-8530-af6b6c8fb46a)

For some reason, the year part is lost completely, and the month part is moved from the center to the far right. Notice the dots in the middle. Does anyone know what might be wrong here?

User version: 5.0.9-beta.35

**Comment by RobinHerbots** [comment]
@stsrki ,

The problem is like 
![image](https://github.com/RobinHerbots/Inputmask/assets/318447/3d49a078-11aa-45d6-a8f4-9af9ed3829c9)

Not yet implemented :)

**Comment by stsrki** [comment]
Any change it could be done in a timely manner?

Ps. Would you be interested in working on contractor basis for this, and any future requests?

**Comment by RobinHerbots** [comment]
@stsrki,

Working on contract basis is not that simple as just saying yes, .... a donation can change priorities ;-)

Anyway, I did a first attempt for the implementation.
Can you have a try.  You need to take the file from the dist folder.

**Comment by stsrki** [comment]
> a donation can change priorities ;-)

Will do :)

---

Anyways. There are still some issue.

1. The long month with the format `mmmm/dd/yyyy` is fully broken. See an image. There are some extra tokens in the middle of the mask
2. The short format, `mmm/dd/yyyy` works for all month names except for the `dec`. I cannot write it.

![image](https://github.com/RobinHerbots/Inputmask/assets/900302/623b36dc-895a-48d4-bc95-abe6408c2b0f)

**Comment by RobinHerbots** [comment]
#2394

**Comment by stsrki** [comment]
1. Writing `dec` now works. But there is now a problem when we try to enter an invalid value. To reproduce just write `jan` and then `4`.

![image](https://github.com/RobinHerbots/Inputmask/assets/900302/fbd299d6-24e2-43bd-98c3-ec7fa4e2b3ed)

---

2. Regarding the long format, `mmmm/dd/yyyy`. It still shows the wrong mask.

![image](https://github.com/RobinHerbots/Inputmask/assets/900302/5e12a8eb-b7fb-4661-be27-ec7dd710f9e1)

**Comment by RobinHerbots** [comment]
Also see #2277

**Comment by RobinHerbots** [comment]
@stsrki ,
Can you have a try with v5.0.9-beta.45.

**Comment by stsrki** [comment]
I've tried v5.0.9-beta.45, but unfortunately, the same errors are still happening.

**Comment by RobinHerbots** [comment]
Can you remove the placeholder property and try the long datetime mmmm/dd/yyyy

**Comment by RobinHerbots** [comment]
I didn't tested the first issue yet.
I will have a look at that too.

**Comment by stsrki** [comment]
Without the placeholder, it looks like this

![image](https://github.com/RobinHerbots/Inputmask/assets/900302/e2d09867-a203-4533-88df-01b7f885d762)

**Comment by RobinHerbots** [comment]
Are you sure you are using the latest version?  Can you create a codepen or fiddle.

**Comment by stsrki** [comment]
Yes, I have downloaded the latest version. Also, I cleared the cache to make sure the latest files are being used.

> Can you create a codepen or fiddle.

Give me some time to do so.

**Comment by RobinHerbots** [comment]
Directly try with 5.0.9-beta.46, this fixes the first issue.

**Comment by stsrki** [comment]
Can confirm the first issue is now fixed 🎉

**Comment by stsrki** [comment]
Hello @RobinHerbots 

Since this is the continuation of the same feature, I don't think there is a need to open a new issue.

Input masks now mostly work, except for the long formats. However, the main issue that we got reported by the users is that the edit mask is case-sensitive.

For example:

Works if you type in for 7th July 1967,

07 Jul 1967

or

7 Jul 1967

But not

07 JUL 1967

or 07 jul 1967

Seems the month name is case-sensitive.

it's hard to get the user to type Jul in the correct case (capital J, lowercase ul).

---

PS. the contractor offer is still open if you're willing to do so. Otherwise, donations are also OK but it gets complicated when paying with the company.

**Comment by RobinHerbots** [comment]
@stsrki,

Strange, using inputFormat: dd mmm yyyy seems to accept Jul jul JUL even jUL JuL, ... UX wise this is not good, 
should I force it to lowercase? whatever you type?

For the long datetime format, I know exactly what is the problem, but I still need to find the time to figure, how to deal with that.

**Comment by stsrki** [comment]
Well, from the regular user perspective, they should not bother with writing the exact title-cased names. So making it case-insensitive would be the best way forward. To have it accept any value, Jul jul JUL, etc.

**Comment by RobinHerbots** [comment]
Hi @stsrki ,

I did some fixes for the long date format.

Can you have a try with the latest beta.

Best regards,
Robin

**Comment by stsrki** [comment]
Hello, sorry for not responding sooner. I was out of the town.

Anyway, I tried the new version, and I don't think it still works. Here are my observations. (Image for context)
 
![image](https://github.com/RobinHerbots/Inputmask/assets/900302/d28b3f14-f72b-4972-ae3b-8769eeb8ce9b)

![image](https://github.com/RobinHerbots/Inputmask/assets/900302/8795aa4c-1b93-493a-840c-acfff970bffd)

1. The long-date mask is still invalid. Notice the `/ry/` in the mask
2. After I type the month name, it changes to an invalid name. `Februa0y`
3. For some reason, it now shows an input mask below the input. Is this for debugging purposes?
4. There are a lot of console logs(see image)

![image](https://github.com/RobinHerbots/Inputmask/assets/900302/c4f3b392-2920-43ef-8031-b7223130d4e3)

**Comment by RobinHerbots** [comment]
Grr, I forgot to remove the console .log ;-)

Ok I tested with dd mmmm yyyy, there it should work ok, when using mmmm dd yyyy indeed I see the problem.

**Comment by RobinHerbots** [comment]
@stsrki ,

Tadaa, another attempt v5.0.9-beta.53

**Comment by stsrki** [comment]
Unfortunately, I still see the same problem 😅

The mask is `mmmm/dd/yyyy`.

![image](https://github.com/RobinHerbots/Inputmask/assets/900302/1902bf5e-52c5-4643-9381-6970e7304b09)

**Comment by RobinHerbots** [comment]
Can you have a try with this codepen.

https://codepen.io/robinherbots/pen/VwNbmNP

Btw when using the colormask.js, you also need to include the colormask.css (and it is still experimental, .... awaiting some feedback, from someone, ...)

**Comment by stsrki** [comment]
The codepen seems to work.

> Btw when using the colormask.js, you also need to include the colormask.css (and it is still experimental, .... awaiting some feedback, from someone, ...)

Is this why the text shows bellow the input? I can review it, just let me know the details.

- How to enabled/disable it?
- Can I control the colors?
- anything else I need to know?

**Comment by RobinHerbots** [comment]
@stsrki ,
For the color mask we can best continue on #2310.

The codepen is working so I can conclude this issue is fixed?

**Comment by stsrki** [comment]
Maybe not just yet. While the codepen works it is really basic example so I went to see what is different from my code. With only `inputFormat` it works. But when I also assign the placeholder then it doesn't work.

Just use this on codepen and you will see it:

```js
Inputmask("datetime", {
		inputFormat: "mmmm/dd/yyyy",
		placeholder: "mmmm/dd/yyyy",
	}).mask("input");
```

**Comment by RobinHerbots** [comment]
Yes, true.  To be able to handle the dynamic length in the long date format the placeholder is generated based on the inputformat, but this only happens when not providing a placeholder of your own.  The best approach will be ignoring the provided placeholder in this case.

Or is there a case for a custom input placeholder in the datetime alias?  I will currently ignore when using the long date format.

**Comment by stsrki** [comment]
In our project, developers can define the placeholders as they wish. So there is a need for it to work along with `inputFormat`.

**Comment by RobinHerbots** [comment]
@stsrki ,

Version 5.0.9-beta.67 can handle custom placeholders for the datetime alias.

Can you have a try.

**Comment by stsrki** [comment]
I can confirm this is now working properly 🎉

@RobinHerbots, thank you for not giving up!
