### ISSUE TITLE
FN key problem

### ISSUE THREAD

**Issue by heavymagic** [RobinHerbots/jquery.inputmask#2760]
When I use the FN features on my keyboard within the input, it writes the commands of those features. For example, when I want to mute the sound, it writes 'AudioVolumeMute' as shown in the visual.

![2023-12-10 02_00_26-Inputmask documentation — Mozilla Firefox](https://github.com/RobinHerbots/Inputmask/assets/48868439/5a215c72-69c8-47cb-ae74-93ccadc1eaed)

- OS: Windows 11
- Browser: Firefox - Chrome
- Inputmask version: 5.0.9-beta.46
- Logitec MX Keys S

**Comment by heavymagic** [comment]
thanks...

**Comment by RobinHerbots** [comment]
@heavymagic ,

Version 5.0.9-beta.52 should fix the issue. Can you have a try and give feedback.

Beste regards,
Robin
