### ISSUE TITLE
Unexpected character removed

### ISSUE THREAD

**Issue by jhonimaike** [RobinHerbots/jquery.inputmask#2765]
Describe the bug
If I set a mask with group separator to "." and decimal separator in ","
When trying to remove the decimal digits and the decimal separator, the library also removes the last character of the integer value and moves the decimal separator "," to the place of the group separator

To Reproduce
Steps and link to sandbox. You can use [jsfiddle](https://jsfiddle.net/euEmail/5rkum7t0/1/)

Expected behavior
It should maintain the value correctly, not eliminating the last digit of the entire value

https://github.com/RobinHerbots/Inputmask/assets/42501674/08de7c3d-1823-493d-8ce9-1a04cbb8bca2

**Comment by Techn1c4l** [comment]
Set "substituteRadixPoint" option to false. You need it to be disabled since you are using different group and decimal separators. Not sure how, but it does fix the issue.
Also, not sure why you have those event handlers. If you need a number type value, use "unmaskAsNumber" option.

**Comment by jhonimaike** [comment]
thanks! It's working fine!
But why is this option not present in the documentation? (or I just didn't find it)

**Comment by RobinHerbots** [comment]
@jhonimaike, @Techn1c4l,
I will investigate why, because disabling that option shouldn't be needed.

**Comment by RobinHerbots** [comment]
@jhonimaike, @Techn1c4l,

The latest beta fixes the issue.
https://jsfiddle.net/wpnk54o9/
