### ISSUE TITLE
The inputmask is autocompleted to the min value when deleting the radix point

### ISSUE THREAD

**Issue by ersib** [RobinHerbots/jquery.inputmask#2773]
- Bug description:
I am using the options below for an inputmask instance. My input accepts a decimal value within a given range. 
`{
    "alias": "decimal",
    "min": 35,
    "max": 200,
    "digits": 2,
    "rightAlign": false,
    "allowMinus": false,
    "showMaskOnHover": false,
    "showMaskOnFocus": false,
    "jitMasking": true,
    "shortcuts": null
}`
In the image below I describe some situations where if I delete the radix point, a reevaluation is performed which sets the value to the predefined minimum value. I would like the value to remain unchanged and to allow the user to continue typing.

![inputmaskRadixPoint](https://github.com/RobinHerbots/Inputmask/assets/57100291/bd244f98-fabe-476c-8fea-d115f4a6bd75)

When debugging the inputmask plugin code, I found that the method which is responsible for this reevalution is onKeyDown() and particularly the highlighted line in dist/inputmask.js.

![image](https://github.com/RobinHerbots/Inputmask/assets/57100291/7a71bd24-ffb7-427c-8243-e82d7993301c)

- OS: Windows 10
- Browser: Chrome Version 121.0.6167.161 (Official Build) (64-bit)
- Inputmask version: 5.0.8

Thank you very much!

**Comment by Techn1c4l** [comment]
The only workaround I've managed to find is using the `digitsOptional: false`. Actually, this is an important issue. I think the `noValuePatching` option should allow us not to patch the value while we're typing.

**Comment by RobinHerbots** [comment]
@ersib,

This issue is fixed in v5.0.10-beta.1
