### ISSUE TITLE
ALT codes

### ISSUE THREAD

**Issue by daniel4ing** [RobinHerbots/jquery.inputmask#2779]
Whenever I use characters with accents, the word 'clear keeps' being added to the field.

For example: When typing ALT + 0235, the word 'clear' appears after pressing the 3, followed by the 'ë' after pressing the 5.

https://i.gyazo.com/1102e229e5fa6bfb7ff987e097ab423d.png

- OS: Windows 11 Home 64-bit
- Browser: Opera, Edge and Chrome
- Inputmask version: demo page & Inputmask-5.0.9-beta.45

**Comment by Techn1c4l** [comment]
I'm not able to input characters using Alt codes in Edge, Chrome or Firefox in any Inputmask field on my system. Which language is your OS?

**Comment by daniel4ing** [comment]
It's set to English (United States), and the numbers are typed, by using the numeric keypad.

**Comment by Techn1c4l** [comment]
Can you try to reproduce this on another PC?

**Comment by daniel4ing** [comment]
On the PC, the ALT codes work appropriately on any other input field, no matter the website or app. And only on the inputmask fields, does it add the word 'clear', with the ë behind it.

On a laptop, the ALT codes work everywhere. No matter the website or app, except for the inputmask fields. Where it doesn't seem to even register the ALT functionality. It just outputs the numbers (0235).

- OS: Windows 10 Home 64-bit
- Browser: Firefox

I tested this with a very basic rules. `$("#field_name").inputmask({ casing: "title" });`. This will still produce the 'clear'.

However,`$("#field_name").inputmask({  });` will display the 'ë'

**Comment by daniel4ing** [comment]
Ok, the clear happens when you have numlock toggled, and type ALT + NUM5. I didn't know I had it active, and I never knew there was a ALT + NUM5 clear thing. Especially confusing since the ALT codes still appear.

ALT+ NUM2 and ALT + NUM 8 seem to be tied to scrolling through the autofill information, for certain fields. So, I'm guessing NUM0 turns into INS, causing for even more headaches.

Sorry for the inconvenience.

**Comment by RobinHerbots** [comment]
@daniel4ing ,

Version 5.0.9-beta.52 should fix the issue.  Can you have a try and give feedback.

Beste regards,
Robin

**Comment by daniel4ing** [comment]
With the Numlock on and off, the ALT codes seem to work perfectly.

In the first few tests, there were still some issues when the NUMLOCK was deactivated, but after working with it for a bit, I've not been able to reproduce those same issues. The clear doesn't appear any more, but there were still some issues regarding the autofill becoming the prominent functionality of the field, but as stated, I'm not able to reproduce this at the moment. 

I'll keep testing, and if any issues occur, I'll let you know. But it seems that you've fixed my issue :)

**Comment by RobinHerbots** [comment]
@daniel4ing ,

Ok great, I will close this issue then.
