### ISSUE TITLE
Pressing the Win button

### ISSUE THREAD

**Issue by tanya-avtey** [RobinHerbots/jquery.inputmask#2780]
Hi. When you press the Win key, if the field is in focus, the OS is printed in the field. How can this situation be corrected?
![546a4-clip-13kb](https://github.com/RobinHerbots/Inputmask/assets/84872382/109a1d33-63e9-4abd-8e2d-81c859c04017)

**Comment by RobinHerbots** [comment]
Hi @tanya-avtey,

Version 5.0.9-beta.52 should fix the issue.  Can you have a try and give feedback.

Beste regards,
Robin

**Comment by tanya-avtey** [comment]
Thanks! The problem is solved.
