### ISSUE TITLE
Allow Aplhanumeric, space, dot and line

### ISSUE THREAD

**Issue by SiKth** [RobinHerbots/jquery.inputmask#2782]
Hi,
I use this setup: 
`<input type="text" data-inputmask-mask="[*]" data-inputmask-greedy="true" data-inputmask-placeholder="_" data-inputmask-repeat="8">`

How do I allow all letters, numbers and space and - and . ? 
Right now I only have the * for alphanumeric.

Thanks!

**Comment by Techn1c4l** [comment]
Use `regex` option instead of `mask` like this:
`<input type="text" data-inputmask-regex="[A-Za-z0-9\-\.\?]" data-inputmask-greedy="true" data-inputmask-placeholder="_" data-inputmask-repeat="8">`

**Comment by SiKth** [comment]
Works great, thanks!
