### ISSUE TITLE
Form Reset/Submit DOM Memory Leak

### ISSUE THREAD

**Issue by melloware** [RobinHerbots/jquery.inputmask#2783]
- Describe the bug

Similar to this old issue: https://github.com/RobinHerbots/Inputmask/issues/1466

I am using jQuery InputMask and if I call `jq.inputmask("remove");` I can see detached `HTMLInputElement` in memory and its because of the InputMask `reset` and `submit` events.

![image](https://github.com/RobinHerbots/Inputmask/assets/4399574/80f64dbe-1678-4fb6-a598-2cb5da8aa3fc)

If I call `jq..inputmask('remove').inputmask(maskCfg);`  3 times I now see this..

![image](https://github.com/RobinHerbots/Inputmask/assets/4399574/c2c64ee7-44c8-458b-a434-3d66618777d6)

You can see its got 3 references so the garbage collector can never clean up the Detached DOM Element.

- OS: Windows 11
- Browser: Chrome /Edge latest
- Inputmask version: latest 5.0.9 rev 50

**Comment by RobinHerbots** [comment]
Hi @melloware ,

I tried to reproduce what you see, but failing (I must be missing something small).  Can you provide a minimal example in a fiddle.
I only see
![image](https://github.com/RobinHerbots/Inputmask/assets/318447/ed2f4e17-a965-474b-a0ab-7a0d30ddef8c)

Anyway I already have a guess where to release those form events, but I want to be sure.

**Comment by melloware** [comment]
i may have to reproduce it with my exact code but I can provide a reproducer although it may be in `Maven-Java` let me try and reproduce.

**Comment by melloware** [comment]
OK now I am having trouble reproducing it.  Let me close this until I can reproduce it.

**Comment by RobinHerbots** [comment]
`   if (["submit", "reset"].includes(eventName)) {
            if (input.form !== null) $(input.form).off(eventName, ev);
          } else {`

normally this should deal with it, and is already present in de codebase
