### ISSUE TITLE
Is there a way to hide placeholder hyphens and only show them when the characters are entered?

### ISSUE THREAD

**Issue by hexerus** [RobinHerbots/jquery.inputmask#2802]
Using the placeholder option:
`<script>
    $('#phone').inputmask('999-99-9', {'placeholder': ''});
</script>`
has disabled the underscore placeholders, but not the dashes.
Image 1 (field not in focus, correct):
![Screenshot 2024-07-04 115951](https://github.com/RobinHerbots/Inputmask/assets/47005060/a4a4f959-77e8-434b-b655-5881250c1a2e)
Image 2 (field in mouse focus, these are the dashes I want to hide):
![Screenshot 2024-07-04 120005](https://github.com/RobinHerbots/Inputmask/assets/47005060/931bd87f-a992-4474-a650-d5eccc78e52e)
Image 3 (only show them when the characters are entered up to that point in green, not show the one in red):
![Screenshot 2024-07-04 120014](https://github.com/RobinHerbots/Inputmask/assets/47005060/124eb030-ad92-4c6d-85d6-da14f9f7ba32)

- OS: Windows 11
- Browser: Chrome 124
- Inputmask version: 5.0.10

**Comment by Techn1c4l** [comment]
Use `showMaskOnFocus`, `showMaskOnHover` and `jitMasking` options like this:
```
$(function() {
  $('#myInput').inputmask('999-99-9',
  {
      placeholder: '',
      showMaskOnFocus: false,
      showMaskOnHover: false,
      jitMasking: true
  });
});
```

**Comment by hexerus** [comment]
`jitMasking: true` appears to works alone on itself, thanks.
